# Generated by Django 3.1.6 on 2021-03-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Watches', 'Watches'), ('Jewelry', 'Jewelry'), ('Engagement & Wedding', 'Engagement & Wedding'), ('Electronics', 'Electronics'), ('Phones & Accessories', 'Phones & Accessories')], max_length=250)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
