# Generated by Django 3.1.6 on 2021-03-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retechecommerce', '0002_auto_20210301_0914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufactures',
            new_name='Manufacture',
        ),
    ]
