# Generated by Django 3.1.6 on 2021-03-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retechecommerce', '0003_auto_20210301_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Watches', 'Watches'), ('Jewelry', 'Jewelry'), ('Engagement & Wedding', 'Engagement & Wedding'), ('Electronics', 'Electronics'), ('Phones & Accessories', 'Phones & Accessories')], max_length=250)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True, null=True)),
                ('pic', models.ImageField(default='images/items/default.png', upload_to='images/items/upcoming')),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
