# Generated by Django 3.1.6 on 2021-03-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retechecommerce', '0005_auto_20210301_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='link',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
