# Generated by Django 3.1.7 on 2021-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retechecommerce', '0007_auto_20210301_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('Message', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
