# Generated by Django 3.1.7 on 2021-03-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retechecommerce', '0008_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
    ]
