# Generated by Django 3.1.7 on 2021-03-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0002_auto_20210314_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
