# Generated by Django 3.1.7 on 2021-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0010_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(to='mainstore.WishListItem'),
        ),
    ]
