# Generated by Django 3.1.7 on 2021-03-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0011_auto_20210315_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
            ],
        ),
    ]
