# Generated by Django 3.1.7 on 2021-03-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0014_auto_20210319_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(default='retechmall@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
