# Generated by Django 3.1.7 on 2021-03-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0017_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
            ],
        ),
    ]
