# Generated by Django 3.1.7 on 2021-03-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0020_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
