# Generated by Django 3.1.7 on 2021-03-22 17:26

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainstore', '0021_delete_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-timestamp'], 'verbose_name': 'wishlist', 'verbose_name_plural': 'wishlists'},
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'item')},
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
