# Generated by Django 3.1.7 on 2021-03-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0025_auto_20210322_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
